baseurl = "/"
languageCode = "en-us"
title = "H. Parker Higgins"
theme = "hugo-theme-casper"
disqusShortname = "hphiggins-com"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Digital Director * Project Management * Digital Marketing"
  cover = "images/cover.jpg"
  author = "Valère JEANTET"
  authorlocation = "Salt Lake City, Utah"
  authorwebsite = "https://hphiggins.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  # githubName = "h-parker-higgins"
  twitterName = "parkerhiggins"
  facebookName = "parker.higgins.12"
  linkedinName = "h-parker-higgins-971b375b"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "parkerhiggins"
